name = "stm32f4xx_m"
provides = ["stm32=1.0"]
# Provides STM32.* and STM32_SVD.* packages in stm32.gpr

description = "Board support for STM32F4XX_M"
version = "0.1.0-dev"

authors = ["Max Reznik"]
maintainers = ["Max Reznik <reznikmm@gmail.com>"]
maintainers-logins = ["reznikmm"]
project-files = ["gnat/stm32f4xx_m.gpr"]

[configuration]
output_dir = "gnat"
generate_ada = false
generate_c = false

[build-switches]
development.optimization = ["-O0"]
development.style_checks = ["-gnaty"]
development.contracts = "Yes"
"*".ada_version = "Ada2022"

[configuration.values]
cortex_m.core = "m4f"

[[depends-on]]
hal = "~0.4.0"
gnat_arm_elf = "^13.2"
cortex_m = "~0.6.0-dev"
adl_middleware = "~0.3.0-dev"
embedded_components = "~0.3.0-dev"

[origin]
commit = "31433839ea04aabe68c624fa687dbc52c610add4"
url = "git+https://github.com/reznikmm/Ada_Drivers_Library.git"

